### ISSUE TITLE
Template example not working

### ISSUE THREAD

**Issue by zemenfes-afk** [Interlin-q/Interlin-q#42]
i try to run thr template.py on my pycharm 3.9 but it gives me the error from thread

starting...
Exception in thread Thread-25:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zemen\PycharmProjects\Interlin-q\interlinq\components\computing_host.py", line 540, in perform_schedule
    self._prepare_qubits(operation)
  File "C:\Users\zemen\PycharmProjects\Interlin-q\interlinq\components\computing_host.py", line 290, in _prepare_qubits
    self.add_data_qubit(self.host_id, qubits[qubit_id], qubit_id)
  File "C:\Users\zemen\PycharmProjects\QuNetSim\qunetsim\components\host.py", line 1322, in add_data_qubit
    self._qubit_storage.add_qubit_from_host(qubit, Qubit.DATA_QUBIT, host_id)
  File "C:\Users\zemen\PycharmProjects\QuNetSim\qunetsim\objects\storage\quantum_storage.py", line 222, in add_qubit_from_host
    raise ValueError("Qubit with these parameters already in storage!")
ValueError: Qubit with these parameters already in storage!
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zemen\PycharmProjects\Interlin-q\interlinq\components\computing_host.py", line 540, in perform_schedule
    self._prepare_qubits(operation)
  File "C:\Users\zemen\PycharmProjects\Interlin-q\interlinq\components\computing_host.py", line 290, in _prepare_qubits
    self.add_data_qubit(self.host_id, qubits[qubit_id], qubit_id)
  File "C:\Users\zemen\PycharmProjects\QuNetSim\qunetsim\components\host.py", line 1322, in add_data_qubit
    self._qubit_storage.add_qubit_from_host(qubit, Qubit.DATA_QUBIT, host_id)
  File "C:\Users\zemen\PycharmProjects\QuNetSim\qunetsim\objects\storage\quantum_storage.py", line 222, in add_qubit_from_host
    raise ValueError("Qubit with these parameters already in storage!")
ValueError: Qubit with these parameters already in storage!

**Comment by stephendiadamo** [comment]
Interlin-q and QuNetSim are two separate projects. This bug is only related to Interlin-q so I removed your comment from the QuNetSim issue you reference. 

I'll look into this issue and will provide feedback.

**Comment by zemenfes-afk** [comment]
yes, it starts to run but the thread stops it from running.

**Comment by zemenfes-afk** [comment]
still no solution?

**Comment by stephendiadamo** [comment]
No not yet, I didn't get a chance to look into this. Probably it will take some weeks before I can investigate this given the ongoing Unitary Hack and my full time work.

**Comment by zemenfes-afk** [comment]
But can we use more than two nodes of host on QKD-BB84 protocol?

**Comment by stephendiadamo** [comment]
I'm not sure what you mean exactly... Is this issue for the Interlin-q project or the QuNetSim project? They are two completely separate projects, so I'm not sure if you're trying to do QKD in Interlin-q or QuNetSim.

**Comment by zemenfes-afk** [comment]
i want to try both interliq and qunetsim, because i need to network more
than two host using QKD BB84 protocol.

**Comment by stephendiadamo** [comment]
Do any of these work for you? https://github.com/tqsd/QuNetSim/tree/master/examples/QKD

**Comment by stephendiadamo** [comment]
I think though in general it would make a lot more sense to work on quantum networking protocols in QuNetSim. Interlin-q is not designed to be used for QKD but QuNetSim is exactly designed for it. I'll close this issue since it seems it's related to QuNetSim only.
